color = input("Enter a color : ")
pluralnoun = input ("Next enter a plural noun : ")
celebrity= input ("Enter a celebrity name : ")
print("Roses are "+ color)
print(pluralnoun+ " are blue")
print("I love "+ celebrity)